name: Code Climate

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Code Climate
        uses: remarkablemark/setup-codeclimate@v2

      - name: Run Test and Upload Coverage
        run: |
          cc-test-reporter before-build
          npm install
          npm test
          cc-test-reporter after-build --exit-code $?
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}