name: Code Climate

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  CodeCoverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm install

      - name: Setup Code Climate
        uses: remarkablemark/setup-codeclimate@v2

      - name: Run Test and Upload Coverage
        run: |
          cc-test-reporter before-build
          xvfb-run -a npm run coverage
          cc-test-reporter after-build --exit-code $?
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}