name: Generate Type Doc
on: 
  push:
    branches:
        - GitHub-Actions
jobs:
  DocGenerator:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
          
        - name: Install modules
          run: npm install

        - name: JSDoc Action (Build)
          uses: andstor/jsdoc-action@v1
          with:
            recurse: true
            output_dir: ./out
            source_dir: ./src
            config_file: jsdoc.json
            template: minami
            front_page: README.md

        - name: Commit and Push Docs
          run: |
            git config --local user.name "github-actions[bot]"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git add ./docs
            git commit -m "Generate documentation"
            git push
    env:
        # GITHUB_TOKEN is provided automatically by GitHub Actions, so you don't need to add it explicitly.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}