name: Generate Type Doc
on: 
  push:
    branches:
        - GitHub-Actions
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Type Doc Action (Build)
        uses: erikyo/tsdoc-action@v1
        with:
            source_dir: ./src/*
            output_dir: ./docs
            front_page: README.md