name: Generate JS Doc
on: 
  push:
    branches:
        - GitHub-Actions
jobs:
  JSDocs:
    runs-on: ubuntu-latest
    steps:
      - name: JSDoc Action
        uses: andstor/jsdoc-action@v1.2.1
        with:
          recurse: true
          output_dir: ./out
    