name: Generate JS Doc
on: 
  push:
  branches:
    - GitHub-Actions
jobs:
  ESLint:
    runs-on: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: JSDoc Action
        uses: andstor/jsdoc-action@v1.2.1
        with:
          source_dir: ./src
          recurse: true
          output_dir: ./out
    