name: Generate Type Doc
on: 
  push:
    branches:
        - GitHub-Actions
jobs:
  DocGenerator:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install modules
          run: npm install

        - name: Generate Documentation
          run: npm run docs

        - name: Commit and Push Docs to gh-pages
          run: |
            git config --local user.name "github-actions[bot]"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git rm -rf .  # Remove everything in the working directory
            git reset -- ./docs  # Restore docs folder from the previous commit
            git add ./docs/*
            git commit -m "Generated documentation"
            git push origin HEAD:gh-pages --force

        # - name: Deploy to GitHub Pages
        #   uses: peaceiris/actions-gh-pages@v3
        #   with:
        #     publish_branch: gh-pages  # GitHub Pages branch
        #     publish_dir: ./docs       # Directory with generated docs
        #     github_token: ${{ secrets.GITHUB_TOKEN }} #secret token for authentication
            
    env:
        # GITHUB_TOKEN is provided automatically by GitHub Actions, so you don't need to add it explicitly.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
