name: Generate Type Doc
on: 
  push:
    branches:
        - GitHub-Actions
jobs:
  DocGenerator:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Install modules
          run: npm install

        - name: Type Doc Action (Build)
          run: npm run docs

        - name: Commit and Push Docs
          run: |
            git config --local user.name "github-actions[bot]"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git add ./docs
            git commit -m "Generate documentation"
            git push

        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            publish_branch: gh-pages  # GitHub Pages branch
            publish_dir: ./docs       # Directory with generated docs
            github_token: ${{ secrets.GITHUB_TOKEN }}
            
    env:
        # GITHUB_TOKEN is provided automatically by GitHub Actions, so you don't need to add it explicitly.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}